name: Pytest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Install build-essential
      run: sudo apt-get install -y build-essential
    - name: Install kitti_iterator
      run: |
        pip install .
    - name: Run tests
      run: python -m pytest --import-mode=append tests/ --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./coverage/reports/
        fail_ci_if_error: false
        verbose: true
        files: ./coverage.xml
